bspec:
  build: .
  command: node_modules/.bin/nodemon index.js
  environment:
    NODE_ENV: development
  ports:
    - '3000:3000'
  volumes:
    - .:/home/app/bspec
    - /home/app/bspec/node_modules
